---
- hosts: wordpress_nodes
  become: yes
  vars:
   wordpress_path: /var/www/wordpress
  tasks:
    - include_tasks: tasks/os-depedencies.yml
    - include_tasks: tasks/wp-install.yml

    - name: "download wordpress"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
    - name: "Unarchive wordpress "
      unarchive:
        src: /tmp/wordpress.zip
        dest: /var/www/wordpress
        remote_src: yes
    - name: "Start service mariadb, if not started"
      service:
        name: mariadb
        state: started
    - name: "Create a new database with name my_database_db"
      mysql_db:
        name: my_database_db
        state: present
    - name: "copy apache cfg"
      template:
        src: templates/blog.conf
        dest: /etc/httpd/conf.d/blog.conf
    - name: "Start service httpd, if not started"
      service:
        name: httpd
        state: restarted
    - name: "copy wp-cofnig.php"
      copy:
        src: templates/wp-config.php
        dest: "{{wordpress_path}}"
